// File: testbench.v
// Generated by MyHDL 0.11.46
// Date: Mon Jun 10 12:10:22 2024


`timescale 1ns/10ps

module testbench (

);

reg [3:0] a;
reg [3:0] b;
wire [4:0] c;

initial begin
    $from_myhdl(
        a,
        b
    );
    $to_myhdl(
        c
    );
    $dumpfile("test.vcd");
    $dumpvars(0, testbench);

end
adder dut(
    a,
    b,
    c
);

endmodule
